### ISSUE TITLE
Can't sync from Crowdin to Payload

### ISSUE THREAD

**Issue by ccapndave** [thompsonsj/payload-crowdin-sync#111]
Hi!  I've got data syncing from Payload to Crowdin, but I don't seem to be able to get it to sync back again.

I've tried `http://localhost:3000/api/crowdin-translations/<id>/review` as described in the README, and I've also tried `http://localhost:3000/api/crowdin-article-directories/<id>/review` (from looking at the code, this seems to be the slug).

However whatever I do I get a 404.

Any advice appreciated!

**Comment by ccapndave** [comment]
Ah, I've just realised that the problem might be that I'm using `next-payload` which hijacks the router (https://github.com/payloadcms/next-payload/issues/73)

**Comment by thompsonsj** [comment]
Thanks for the feedback - I'll get the docs updated with the correct endpoints.

Those endpoints represent the quickest possible way I could figure out to sync translations at the time. It needs to be improved, and I plan to look at that.

https://github.com/thompsonsj/payload-crowdin-sync/pull/113 is released in https://www.npmjs.com/package/payload-crowdin-sync/v/0.18.0. Let me know if that works for you but otherwise I'll look into a better way of exposing methods to update translations.
